### PR TITLE
Added missing German translations to PR tips. Fixed a typo or two.

### PR DESCRIPTION
**Pull request by PrStrategos**
Took care of a first small batch of missing translations into German concerning the PR tips. Hope everything is OK.

### CODE REVIEW

**Comment by AncientMan2002** [comment]
:+1: 

Also, make sure you grab this commit 0c07c3a8 in your fork as there was an issue with line endings causing some messed up files. Good stuff, look forward to more :)

**Comment by AncientMan2002** [comment]
Also, just so you're aware, the .utxt files must be in UTF-16LE encoding. Your commit was in UTF-8. I have fixed this in 4662a2b1.

For future reference, use Notepad++ to edit these files, and make sure down the bottom right it says "DOS\Windows, UCS-2 Little Endian". If not, you can go Encoding -> Convert To UCS-2 Little Endian.

Cheers

**Comment by PrStrategos** [comment]
> Good stuff, look forward to more :)

No problem :). I'll see if I can find some more time for the other strings.

> Also, just so you're aware, the .utxt files must be in UTF-16LE encoding. Your commit was in UTF-8. I have fixed this in 4662a2b.
> 
> For future reference, use Notepad++ to edit these files, and make sure down the bottom right it says "DOS\Windows, UCS-2 Little Endian". If not, you can go Encoding -> Convert To UCS-2 Little Endian.

The thing is: When I open the files in Sublime Text using UTF-16 LE I get a scrambled mess (Chinese characters and other stuff). For some reason this only happens when editing the git checked-out files. If I download the raw files via Chrome I can edit them fine as UTF-16 LE. But I don't know if these would then be usable in PR. 

For the commit above I actually used GitHub's inbuilt editor, thinking that it would preserve the encoding. Looks like I thought wrong. I would use Notepad++, but my main OS is Linux. I'll see if I can find another solution to fit my workflow.

**Comment by AncientMan2002** [comment]
Yeah, I noticed that scrambled mess. I committed a fix for that 0c07c3a which should solve the issue. Just pull it into your fork, then re-download your local.

Sublime would be fine to use as well. As long as it's not notepad or something like that, it's all good :)

**Comment by PrStrategos** [comment]
Ah, there we go. It's working fine now. Thanks for the pointer!

**Pull request merged**
